
project_type: "*"
source_dir: /home/z/projects/rag
target_file: /home/z/projects/rag/output.txt

model: v3_chat    
model_max_input_length: 60000    
index_filter_workers: 100
index_build_workers: 100
index_filter_level: 1

execute: true
auto_merge: true
human_as_model: true